@url = http://localhost:4206
	
### FETCH ALL EMPLOYEES
GET {{url}}/employees

### SEND MAIL WITH SPECIFIC EMPLOYEE INFO
POST https://et394-render-test-of-nodemailer.onrender.com/employees/sendmail/3
content-type: application/json

{
	"pin": "2233"
}
	